update: all
pin: True
schedule: "every week"
search: True
requirements:
  - requirements.txt:
      update: all
  - requirements_dev.txt:
      update: all
label_prs: pyup
assignees:
 - alecpm
close_prs: True
