update: all
pin: True
search: False
requirements:
  - requirements.txt:
      update: all
  - requirements_dev.txt:
      update: all
label_prs: pyup
branch_prefix: pyup/
pr_prefix: "PyUp "
assignees:
 - alecpm
close_prs: True
